### ISSUE TITLE
ReadME Alt+F2

### ISSUE THREAD

**Issue by fablevi** [yousafesaeed/window-on-top#1]
Hi! Nice fork of mine, i like it :)

The problem: Alt+ F2 reload only works on X11. On Wayland you need to log out and log in for reload the GNOME SHELL.
Please update the ReadMe, thx <3

Levi

**Comment by yousafesaeed** [comment]
Hi Levi, It's not a fork, but rather a separate project. But I appreciate your observation.

Will update README soon, Thank you.

Cheers, Yousef
